### PR TITLE
Update lxml version to 4.9.4

### PR DESCRIPTION
**Pull request by DeltaFox0018**

### CODE REVIEW

**Comment by johnnybegood** [comment]
Breaking change for the new release? @DeltaFox0018

**Comment by DeltaFox0018** [comment]
after updating to version 2024.1.0 of home assistant and restarting the server, the error in the logs was that it couldn't find lxml:4.9.3 even after trying to reinstall integration. the only one was to update the lxml version

**Comment by DeltaFox0018** [comment]
Is it possible to create release version 1.2.4 so as to also update HACS?

**Comment by johnnybegood** [comment]
Yes, but currently not near my laptop and can only do this on a laptop.

**Pull request merged**
